class Clinic < ApplicationRecord
    has_many :pcr_inspections, dependent: :destroy

    enum city: { 
        adachi: 1,
        arakawa: 2,
        itabashi: 3,
        edogawa: 4,
        ota: 5,
        katsushika: 6,
        kita: 7,
        koto: 8,
        shinagawa: 9,
        shibuya: 10,
        sinjuku: 11,
        suginami: 12,
        sumida: 13,
        setagaya: 14,
        taito: 15,
        tyuo: 16,
        chiyoda: 17,
        toshima: 18,
        nakano: 19,
        nerima: 20,
        bunkyo: 21,
        minato: 22,
        meguro: 23,
        akishima: 24,
        akiruno: 25,
        inagi: 26,
        oume: 27,
        okutama: 28,
        kiyose: 29,
        kunitachi: 30,
        koganei: 31,
        kokubunji: 32,
        kodaira: 33,
        tachikawa: 34,
        tama: 35,
        tyohu: 36,
        nishitokyo: 37,
        hachioji: 38,
        hamura: 39,
        higashikurume: 40,
        higashimurayama: 41,
        higashiyamato: 42,
        hino: 43,
        hinode: 44,
        hinohara: 45,
        hutyu: 46,
        hussa: 47,
        machida: 48,
        mizuho: 49,
        mitaka: 50,
        musashino: 51,
        musashimurayama: 52,
        aogashima: 53,
        oshima: 54,
        ogasawara: 55,
        koudusima: 56,
        toshimamura: 57,
        nijima: 58,
        hachijo: 59,
        mikurajima: 60,
        miyake: 61
    }
end
